In [2]:
import numpy as np
import pandas as pd
#import one hot encoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [23]:
#convert excel file to csv
df = pd.read_csv('mall.csv')

In [24]:
df = pd.read_csv('mall.csv')
print(df.head())

   Region Age   Income Online Shopper
0   India  49  86400.0             No
1  Brazil  32  57600.0            Yes
2     USA  35   6400.0             No
3  Brazil  43  73000.0             No
4     USA  45      NaN            Yes

In [25]:
#handling missing values
df.isnull().sum()
df.replace('?', np.nan, inplace=True)

   Region  Age    Income Online Shopper
0   India   49   86400.0             No
1  Brazil   32   57600.0            Yes
2     USA   35    6400.0             No
3  Brazil   43   73000.0             No
4     USA   45       NaN            Yes
5   India   40   69000.0            Yes
6  Brazil  NaN  629890.0             No
7   India   53   68590.0            Yes
8     NaN   55   63682.0             No
9   India   42  727289.0            Yes

In [26]:
df['Online Shopper'] = df['Online Shopper'].replace({'Yes': 1, 'No': 0})

In [27]:
df

   Region  Age    Income Online Shopper
0   India   49   86400.0              0
1  Brazil   32   57600.0              1
2     USA   35    6400.0              0
3  Brazil   43   73000.0              0
4     USA   45       NaN              1
5   India   40   69000.0              1
6  Brazil  NaN  629890.0              0
7   India   53   68590.0              1
8     NaN   55   63682.0              0
9   India   42  727289.0              1

In [28]:
X = pd.get_dummies(X, columns=['Region'], drop_first=True)

In [32]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Region'] = le.fit_transform(df['Region'])

In [33]:
print("Training set size:", X_train.shape)

Training set size: (8, 4)

In [34]:
print("testing data size:", X_test.shape)

testing data size: (2, 4)

In [35]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[['Region']] = scaler.fit_transform(df[['Region']])

In [36]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

In [37]:
scaler = StandardScaler()
df[df.columns] = scaler.fit_transform(df)

In [39]:
#split the data into training and testing sets
x = df.drop('Online Shopper',axis=1)
y = df['Online Shopper']
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2, random_state=42)